-- MySQL Script generated by MySQL Workbench
-- Thu Apr 24 12:23:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cul_dampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cul_dampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cul_dampolla` DEFAULT CHARACTER SET utf8mb4 ;
USE `cul_dampolla` ;

-- -----------------------------------------------------
-- Table `cul_dampolla`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`address` (
  `id_address` SMALLINT UNSIGNED NOT NULL,
  `street_name` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL,
  `number` SMALLINT UNSIGNED NOT NULL,
  `floor` TINYINT NOT NULL,
  `door` TINYINT UNSIGNED NULL DEFAULT NULL,
  `city` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL,
  `postal_code` CHAR(5) NOT NULL,
  `country` VARCHAR(40) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`id_address`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`customers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(40) CHARACTER SET 'utf8mb4' NOT NULL,
  `register_date` DATE NOT NULL,
  `address_id_address` SMALLINT UNSIGNED NOT NULL,
  `recommender_id` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `address_id_address`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_customers_address1_idx` (`address_id_address` ASC) VISIBLE,
  INDEX `fk_customers_customers1_idx` (`recommender_id` ASC) VISIBLE,
  CONSTRAINT `fk_customers_address1`
    FOREIGN KEY (`address_id_address`)
    REFERENCES `cul_dampolla`.`address` (`id_address`),
  CONSTRAINT `fk_customers_customers1`
    FOREIGN KEY (`recommender_id`)
    REFERENCES `cul_dampolla`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`employees` (
  `employee_id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`providers` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `fax` VARCHAR(15) NULL DEFAULT NULL,
  `NIF` CHAR(9) NOT NULL,
  `address_id_address` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `address_id_address`),
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  INDEX `fk_providers_address1_idx` (`address_id_address` ASC) VISIBLE,
  CONSTRAINT `fk_providers_address1`
    FOREIGN KEY (`address_id_address`)
    REFERENCES `cul_dampolla`.`address` (`id_address`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`brand_has_glass_models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`brand_has_glass_models` (
  `brand_id` INT NOT NULL AUTO_INCREMENT,
  `brand_name` VARCHAR(45) NOT NULL,
  `providers_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`brand_id`, `providers_id`),
  INDEX `fk_brand_has_glass_models_providers1_idx` (`providers_id` ASC) VISIBLE,
  CONSTRAINT `fk_brand_has_glass_models_providers1`
    FOREIGN KEY (`providers_id`)
    REFERENCES `cul_dampolla`.`providers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`glasses` (
  `model` INT UNSIGNED NOT NULL,
  `left_glass_graduation` FLOAT NOT NULL,
  `right_glass_graduation` FLOAT NOT NULL,
  `type` ENUM('flotant', 'pasta', 'metal·lica') NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `left_glass_color` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  `right_glass_color` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  `price` FLOAT UNSIGNED NOT NULL,
  `brand_id` INT NOT NULL,
  PRIMARY KEY (`model`, `brand_id`),
  INDEX `fk_glasses_brand_has_glass_models1_idx` (`brand_id` ASC) VISIBLE,
  CONSTRAINT `fk_glasses_brand_has_glass_models1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `cul_dampolla`.`brand_has_glass_models` (`brand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`sales` (
  `transaction_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `employees_employee_id` INT NOT NULL,
  `customers_id` INT UNSIGNED NOT NULL,
  `glasses_model` INT UNSIGNED NOT NULL,
  `sale_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`transaction_id`, `employees_employee_id`, `customers_id`, `glasses_model`),
  INDEX `fk_sales_employees1_idx` (`employees_employee_id` ASC) VISIBLE,
  INDEX `fk_sales_customers1_idx` (`customers_id` ASC) VISIBLE,
  INDEX `fk_sales_glasses1_idx` (`glasses_model` ASC) VISIBLE,
  CONSTRAINT `fk_sales_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `cul_dampolla`.`customers` (`id`),
  CONSTRAINT `fk_sales_employees1`
    FOREIGN KEY (`employees_employee_id`)
    REFERENCES `cul_dampolla`.`employees` (`employee_id`),
  CONSTRAINT `fk_sales_glasses1`
    FOREIGN KEY (`glasses_model`)
    REFERENCES `cul_dampolla`.`glasses` (`model`))
ENGINE = InnoDB
AUTO_INCREMENT = 151
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
